# Generated by Django 3.0.7 on 2020-08-12 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('P', 'Python'), ('C', 'C++'), ('J', 'Java'), ('c', 'C')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=10000)),
                ('problems', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.Problem')),
                ('programming_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.ProgrammingLanguage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(choices=[('A', 'Accepted'), ('WA', 'Wrong Answer'), ('CE', 'Compilation Error'), ('SF', 'Segmentation Fault')], max_length=2)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iscorrect', models.CharField(choices=[('P', 'Passed'), ('F', 'Failed')], max_length=1)),
                ('submission_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Submission')),
                ('testcase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.TestCase')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Verdict'),
        ),
    ]
