# Generated by Django 3.0.7 on 2020-08-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='programming_language',
        ),
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('Py', 'Python'), ('C++', 'C++'), ('J', 'Java'), ('C', 'C')], default='C', max_length=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProgrammingLanguage',
        ),
    ]
