# Generated by Django 3.0.7 on 2020-08-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_auto_20200817_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
