# Generated by Django 3.0.7 on 2020-08-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_submission_problem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='problem_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
