# Generated by Django 3.0.7 on 2020-08-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0008_auto_20200817_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='problem_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
