# Generated by Django 3.0.7 on 2020-08-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=100, unique=True)),
                ('problem_statement', models.TextField()),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
                ('time_limit', models.IntegerField()),
                ('memory_limit', models.IntegerField()),
                ('testcase_input', models.TextField(null=True)),
                ('testcase_output', models.TextField(null=True)),
                ('problem_level', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=1)),
                ('maximum_marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=100)),
                ('correct_output', models.CharField(max_length=100)),
            ],
        ),
    ]
