# Generated by Django 3.0.7 on 2020-08-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='correct_output',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='input',
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_case',
            field=models.FileField(blank=True, null=True, upload_to='TestCases/'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
