# Generated by Django 3.0.7 on 2020-08-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20200821_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
